### ISSUE TITLE
[Bugs] a couple of bugs

### ISSUE THREAD

**Issue by CrossVas** [Zuxelus/Combo-Armors#2]
1. All CA item's are listed in every Vanilla/NonVanilla Creative Tab;
2. NanoSuit Jetpack is rendered as Diamond Armor when is equiped;
3. CA items are rendered over Vanilla Void Slot (Destroy Slot) in creative mode. 
![2020-12-16_19 31 31](https://user-images.githubusercontent.com/25727222/102384469-6c26d400-3fd5-11eb-9b45-2932ef2bc5e8.png)
![2020-12-16_19 31 42](https://user-images.githubusercontent.com/25727222/102384470-6cbf6a80-3fd5-11eb-9d6a-c36f4b42be32.png)
![2020-12-16_19 31 52](https://user-images.githubusercontent.com/25727222/102384471-6d580100-3fd5-11eb-8d8d-343d328653b2.png)

**Comment by Zuxelus** [comment]
Should be fixed in ComboArmors-1.12.2-0.0.3.jar

**Comment by CrossVas** [comment]
Yeah, just checked. Keep up the great mod. Thank you!
