### ISSUE TITLE
Как можно написать разработчику?

### ISSUE THREAD

**Issue by HiLevel16** [Zuxelus/Combo-Armors#4]
Привет, поделись пожалуйста своими контактами, хочу помочь
Hi, please, share your contacts. I want to help a little

**Comment by Zuxelus** [comment]
Писать в Дискорд. Можно писать в группу мода (https://discord.gg/fJCsmWT) или мне лично. Мой ник Zuxelus#2669.
Ссылка на эту группу так же есть на странице мода в CurseForge.
